const { handleTableData } = require("./tableData");
const {
  saveContactData,
  getContactQueries,
  getTestData,
  saveNewPartyData,
  saveDocketData,
  getCompanyNames,
  getDockets,
  getDataForInvoice,
  getDataToUpadate,
  updateDocketData,
  updateRateList,
  getInvoiceNum,
  signinUser,
  registerUser,
} = require("./urlMapping");
module.exports = {
  "/savecontact": saveContactData,
  "/getcontactqueries": getContactQueries,
  "/testdata": getTestData,
  "/savenewpartydata": saveNewPartyData,
  "/savedocketdata": saveDocketData,
  "/getcompanynames": getCompanyNames,
  "/getdockets": getDockets,
  "/getdataforinvoice": getDataForInvoice,
  "/getdatatoupadate": getDataToUpadate,
  "/updatedocketdata": updateDocketData,
  "/updateratelist": updateRateList,
  "/getinvoicenum": getInvoiceNum,
  "/signin": signinUser,
  "/register": registerUser,
  "/tableData": handleTableData,
};
